server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_book_store
    username: root
    password: root
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: culatao33@gmail.com
    password: mkgs psgm newc gztv
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

email:
  from: culatao33@gmail.com
jwt:
  signerKey: "XcAwK8Rtvw6J8Rds07aAwhsqrsiDqq5OShc8ngOgyuuxWpe83B6rOpZBwif8LCkQ"
  valid-duration: 3600  # in second
  refreshable-duration: 360000 # in seconds
app:
  base-url: http://localhost:8080/api